project:
  type: book
  post-render: tools/strip-polyfill.py
  resources:
    - assets/**
    - "Videos einbinden/**"

book:
  title: "Interaktives Quarto-Workbook Moderne Physik"
  author: "Physik PH Karlsruhe"
  date: today
  chapters:
    - index.qmd
    - 00_konzeption.qmd
    - 01_srt_raum_und_zeit.qmd
    - 01_srt_raum_und_zeit_umbau.qmd
    - 03_srt_impuls_und_energie.qmd
    - 03_srt_impuls_und_energie_umbau.qmd
    - 02_laser_ausflug.qmd
    - 02_laser_ausflug_umbau.qmd
    - references.qmd

lang: de
bibliography: references.bib

format:
  html:
    theme: [cosmo, assets/no-webfont.scss]
    html-math-method:
      method: mathjax
      url: assets/mathjax/tex-svg-full.js
    css:
      - assets/learning-boxes.css
      - assets/fonts/source-sans-pro.css
    include-after-body: assets/toc-in-sidebar.html
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
